# Generated by Django 5.1.1 on 2024-10-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passenger_image',
            field=models.ImageField(blank=True, null=True, upload_to='passenger/passenger_images/'),
        ),
        migrations.AlterField(
            model_name='passengerdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='passenger/passenger_documents/'),
        ),
        migrations.AlterField(
            model_name='passengergeneraldocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='passenger/passenger_general_documents/'),
        ),
        migrations.AlterField(
            model_name='passengerpassport',
            name='passport_scanned_image',
            field=models.FileField(blank=True, null=True, upload_to='passenger/passenger_passport_images/'),
        ),
    ]
