# Generated by Django 5.1.1 on 2024-10-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='agent/agent_documents/'),
        ),
        migrations.AlterField(
            model_name='agentinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agent/agent_images/'),
        ),
        migrations.AlterField(
            model_name='agenttransaction',
            name='bank_transaction_file',
            field=models.FileField(blank=True, null=True, upload_to='agent/agent_transactions/agent_bank_transaction_files/'),
        ),
        migrations.AlterField(
            model_name='agenttransaction',
            name='online_transaction_file',
            field=models.FileField(blank=True, null=True, upload_to='agent/agent_transactions/agent_online_transaction_files/'),
        ),
    ]
