# Generated by Django 5.1.1 on 2024-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_visa', models.IntegerField(blank=True, null=True)),
                ('office', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('collected_data', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_days', models.IntegerField(blank=True, default=0, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='visa_documents/')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
